In [1]:
#完成插值

import numpy as np
import cv2
img = cv2.imread("rice.tif",cv2.IMREAD_GRAYSCALE)

def showimg(img):
    cv2.imshow("hello",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
#双线性插值
h,w = img.shape[:2]

new_h, new_w=50, 100
new_img = np.zeros((new_h,new_w),np.uint8)
y_ratio=h/new_h
x_ratio=w/new_w

for i in range(new_w):
    for j in range(new_h):
        x1=int(i*x_ratio)
        y1=int(j*y_ratio)
        x2=min(x1+1,w-1)
        y2=min(y1+1,h-1)

        a=img[y1,x1]
        b=img[y1,x2]
        c=img[y2,x2]
        d=img[y2,x1]

        dx = i*x_ratio-x1
        dy = j*y_ratio-y1
        
        new_img[j,i]=(1-dx)*(1-dy)*a+(1-dy)*dx*b+dx*dy*c+(1-dx)*dy*d
print(new_img)
showimg(new_img)

[[122  97 104 ... 181 105 100]
 [ 87  99 105 ... 100  93  94]
 [ 97 101  96 ... 100  97 101]
 ...
 [ 51  48  50 ...  55  53  53]
 [ 41  52  57 ...  51  50  51]
 [ 41  54  51 ...  50  47  59]]


In [2]:
#临近插值
h,w = img.shape[:2]
newh,neww=10,100
new_img=np.zeros((newh,neww),dtype=img.dtype)
x_ratio=w/neww
y_ratio=h/newh
for i in range(neww):
    for j in range(newh):
        x = min(round(i*x_ratio),w-1)
        y = min(round(j*y_ratio),h-1)
        new_img[j,i]=img[y,x]
showimg(new_img)



In [3]:
new_img = cv2.resize(img,(50,100),interpolation=cv2.INTER_CUBIC)#这里注意输入宽高的顺序，宽在前，高在后
showimg(new_img)